-- CREATE Comment Table
CREATE TABLE IF NOT EXISTS comment_tb (
    comment_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    author VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL,
    author_position VARCHAR(255) NOT NULL,
    comment_subject VARCHAR(255) NOT NULL,
    comment_text TEXT NOT NULL,
    upVote bigint NOT NULL DEFAULT 0,
    downVote bigint NOT NULL DEFAULT 0
);

-- Rollback for this migration
--DROP TABLE IF EXISTS comment_tb;